services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ["/wait-for-it.sh", "db:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
    working_dir: /app/src
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/toy_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
